//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpediaDal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ErpediaEntities : DbContext
    {
        public ErpediaEntities()
            : base("name=ErpediaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TestTable> TestTables { get; set; }
    
        public virtual ObjectResult<Sp_GetGeneralTest_Result> Sp_GetGeneralTest()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_GetGeneralTest_Result>("Sp_GetGeneralTest");
        }
    }
}
