//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpediaDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTable
    {
        public int Id { get; set; }
        public string TestData1 { get; set; }
        public string TestData2 { get; set; }
    }
}
